-- create_green_contours.sql

CREATE TABLE IF NOT EXISTS public.green_contours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hole_id UUID NOT NULL REFERENCES public.holes(id) ON DELETE CASCADE,
  grid_spacing_feet FLOAT NOT NULL DEFAULT 1.0,
  matrix_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT uq_green_contours_hole_id UNIQUE (hole_id)
);

-- Enable RLS
ALTER TABLE public.green_contours ENABLE ROW LEVEL SECURITY;

-- Select policy: Anyone can read green_contours if they can read the course
-- Since course visibility might be public, or user specific, we can match holes' policy
-- For simplicity, let's allow read for all authenticated users or public if applicable.
-- Assuming standard access:
CREATE POLICY "Enable read access for all users" ON public.green_contours FOR SELECT USING (true);

-- Insert/Update policy: Only authenticated users can insert/update (or course owners)
CREATE POLICY "Enable all access for authenticated users" ON public.green_contours FOR ALL USING (auth.role() = 'authenticated');

-- Function to handle updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS set_green_contours_updated_at ON public.green_contours;
CREATE TRIGGER set_green_contours_updated_at
BEFORE UPDATE ON public.green_contours
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Comment for schema documentation
COMMENT ON TABLE public.green_contours IS 'Caches high-density elevation matrix data (JSON) for generating contour lines via marching squares.';
